services:
  bird:
    image: ghcr.io/minoplhy/pathvector-docker:dev-bird
    container_name: Bird
    entrypoint: ["/start-bird.sh"]
    restart: unless-stopped
    volumes:
      - ./bird:/etc/bird
      - ./rundir:/run:z
      - ./start-bird.sh:/start-bird.sh
    network_mode: host

#  pathvector:
#    image: ghcr.io/minoplhy/pathvector-docker:dev-pathvector
#    container_name: pathvector
#    restart: unless-stopped
#    environment:
#      - KNOT_SOCKET=/rundir/knot/knot.sock
#    volumes:
#      - ./rundir:/rundir:z     # knot.sock will be here
#      - ./bird_bin:/usr/sbin
#      - ./bird:/etc/bird
#      - ./pathvector.yaml:/etc/pathvector.yml
#    depends_on:
#      - bird


  pathvector:
    image: ghcr.io/minoplhy/pathvector-docker:dev-pathvector
    container_name: pathvector
    restart: unless-stopped
    environment:
      - KNOT_SOCKET=/rundir/knot/knot.sock
    volumes:
      - ./rundir:/rundir:z     # knot.sock will be here
      - ./bird_bin:/usr/sbin
      - ./bird:/etc/bird
      - ./pathvector.yaml:/etc/pathvector.yml
    depends_on:
      - bird