# bump number for image rebuild: 3
FROM alpine:latest
RUN apk update
RUN apk upgrade
RUN apk add \
	build-base \
	flex \
	bison \
	autoconf \
	ncurses \
	readline-dev \
	libssh-dev \
    linux-headers
RUN apk add \
	git

WORKDIR /workspace
RUN git clone https://github.com/CZ-NIC/bird

WORKDIR /workspace/bird
RUN git checkout v3.1.4
RUN autoreconf
RUN ./configure --prefix=/usr --sysconfdir=/etc/bird --runstatedir=/run
RUN make
RUN make install

EXPOSE 179/tcp