# bump number for image rebuild: 3
FROM golang:alpine as builder

RUN git clone https://github.com/natesales/pathvector
WORKDIR /workspace/pathvector

RUN git checkout v6.3.2
RUN go build

COPY --from=builder /workspace/pathvector/pathvector /app/

COPY ./crontab /etc/cron.d/pathvector-cron
RUN chmod 0644 /etc/cron.d/pathvector-cron
RUN touch /var/log/cron.log

FROM alpine:latest
RUN apk update
RUN apk upgrade
RUN apk add \
	build-base \
	flex \
	bison \
	autoconf \
	ncurses \
	readline-dev \
	libssh-dev \
    linux-headers
RUN apk add \
	git \
	bash

WORKDIR /workspace
RUN git clone https://github.com/CZ-NIC/bird

WORKDIR /workspace/bird
RUN git checkout v3.1.4
RUN autoreconf
RUN ./configure --prefix=/usr --sysconfdir=/etc/bird --runstatedir=/run
RUN make
RUN make install

EXPOSE 179/tcp

VOLUME /etc/bird
VOLUME /run